apiVersion: v1
kind: Deployment
metadata: this test data
test sample data
data:
  key 1: value
  key1: value111
  key2: value2]
kind: ConfigMap
metadata:
apiVersion: v1
kind: Deployment
metadata: this test data
test sample data
data:
  key1: value1
  key2: value2]
kind: ConfigMap
metadata:
apiVersion: v1
kind: Deployment
metadata: this test data
test sample data
data:
  key1: value1
  key2: value2]
kind: ConfigMap
metadata:
apiVersion: v1
kind: Deployment
metadata: this test data
test sample data
data:
  key1: value1
  key2: value2]
kind: ConfigMap
metadata:
apiVersion: v1
kind: Deployment
metadata: this test data
test sample data
data:
  key1: value1
  key2: value2]
kind: ConfigMap
metadata:
apiVersion: v1
kind: Deployment
metadata: this test data
test sample data
data:
  key1: value1
  key2: value2]
kind: ConfigMap
metadata:
apiVersion: v1
kind: Deployment
metadata: this test data
test sample data
data:
  key1: value1
  key2: value2]
kind: ConfigMap
metadata:
apiVersion: v1
kind: Deployment
metadata: this test data
test sample data
data:
  key1: value1
  key2: value2]
kind: ConfigMap
metadata:
apiVersion: v1
kind: Deployment
metadata: this test data
test sample data
data:
  key1: value1
  key2: value2]
kind: ConfigMap
metadata:
