apiVersion: v1
kind: Deployment
metadata: this test data
test sample data
data:
  key 1: value
  key1: value111
  key2: value2]
kind: ConfigMap
metadata:
  name: example-config
  sdsjkds
  skdks

  sdskdjsdS

  sdskdjsdSs
  ds
  labels:
    app: myapp
data:
  config.yaml: |      
    setting1: true
    setting2: 42    